"""Opt-in real Russian ASR/embedding/search smoke test on macOS (downloads weights).

Run from project root: python -m tests.manual_smoke
Source is synthetic speech generated by macOS, NOT an actual YouTube recording.
Only network downloader is substituted; MLX, ffmpeg, tokenization, E5 and Qdrant are real.
"""
from pathlib import Path
import logging
import shutil
import subprocess
import tempfile
from unittest.mock import patch
from src.config import Config
from src.models import Video
from src.pipeline import Pipeline
from src.urls import canonical_url
from search import semantic_search


def main():
    directory = Path(tempfile.mkdtemp(prefix='papich-russian-smoke-'))
    logging.basicConfig(level=logging.INFO)
    logging.getLogger('httpx').setLevel(logging.WARNING)
    texts = {
        'RUSMOKE0001': ('Деньги и работа', 'Сегодня мы обсуждаем деньги и работу. '
                        'Зарплата приходит каждый месяц. Часть денег я откладываю в сбережения. '
                        'Остальное трачу на еду, квартиру и поездки. Хорошая работа должна '
                        'приносить достойный доход. Важно планировать личный бюджет.'),
        'RUSMOKE0002': ('Кулинария', 'Сегодня готовим овощной суп. Сначала нарежем морковь '
                        'и картофель. Затем вскипятим воду в большой кастрюле. Добавим овощи '
                        'и немного соли. Через двадцать минут суп будет готов. Подаём его '
                        'со свежей зеленью и хлебом.'),
    }
    sources = {}
    for key, (_, text) in texts.items():
        source = directory / f'{key}.aiff'
        subprocess.run(['say', '-v', 'Milena', '-o', str(source), text], check=True)
        sources[key] = source

    def metadata(url, config):
        from src.urls import video_id
        key = video_id(url)
        return Video(key, 'SYNTHETIC TEST: ' + texts[key][0], 'macOS say', url, url)

    def download(video, target, config):
        target.mkdir(parents=True, exist_ok=True)
        result = target / 'source.aiff'
        shutil.copyfile(sources[video.id], result)
        return result

    config = Config(data_dir=str(directory / 'data'), whisper_model='small')
    pipeline = Pipeline(config)
    try:
        with patch('src.downloader.metadata', metadata), patch('src.downloader.download', download):
            assert pipeline.run([canonical_url(key) for key in texts]) == 0
        hits = semantic_search('деньги', config, 2)
        assert hits and hits[0]['video_id'] == 'RUSMOKE0001', hits
        assert 'деньг' in hits[0]['text'].lower(), hits[0]['text']
        print(f"PASS: Russian query retrieved money/work first (score {hits[0]['score']:.4f})")
        print('Synthetic fixtures and evidence:', directory)
        print(hits[0]['text'])
    finally:
        pipeline.close()


if __name__ == '__main__':
    main()
